# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 11fqkk(番茄看看)

on:
  workflow_dispatch:
  schedule:
     - cron: '10 5-15 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/a1564471347/ZQ.git ~/ZQ
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/ZQ
          npm install -g npm
          npm update

      - name: '运行 【番茄看看】'
        if: env.fqkkurl
        run: |
          cd ~/Scripts
          node Task/11fqkk.js
        env:
          fqkkurl: ${{ secrets.fqkkurl }}
          fqkkhd: ${{ secrets.fqkkhd }}
          fqkkck: ${{ secrets.fqkkck }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
